### ISSUE TITLE
Nuevo menú inicial

### ISSUE THREAD

**Issue by yagueto** [codemonsters/dizzy-balloon#29]
### En vez de esa cosa **fea** que pone al principio, que muestre una con las siguientes opciones:

- [x] Jugar
- [x] Instrucciones
- [x] Preferencias
- [x] Salir

Buen día,
Yago

**Comment by yagueto** [comment]
¡Listo! Faltan los botones 2 y 3.

**Comment by yagueto** [comment]
#35 Esto tiene que ver

**Comment by asexto** [comment]
¿Deberíamos añadir "Créditos" como una opción más del menú principal?

**Comment by yagueto** [comment]
Quizás yo lo incluiría en preferencias... :thinking:

**Comment by yagueto** [comment]
Ha sido decidido que vamos a decirle adiós a SUIT. La librería no nos satisface, porque algunas funciones (como el layout) no funcionan bien.

Por lo tanto, nos lo vamos a hacer nosotros mismos. Y punto.
