### ISSUE TITLE
Cambiar color título menú 

### ISSUE THREAD

**Issue by yagueto** [codemonsters/dizzy-balloon#35]
No hay manera de hacerlo. Por favor, que alguien se encarge. :+1:

**Comment by yagueto** [comment]
Estoy en ello. La branch [https://github.com/codemonsters/dizzy-balloon/tree/NuevoMen%C3%BA2](url) trabajo con ello

**Comment by yagueto** [comment]
Listo.

**Comment by asexto** [comment]
Yeah!!!   ᕕ( ᐛ )ᕗ
