### ISSUE TITLE
Sonidos

### ISSUE THREAD

**Issue by asexto** [codemonsters/dizzy-balloon#43]
Sonidos cuando la bomba explota, cuando se planta o lanza, cuando se pierde una vida, cambiamos de nivel...

Valorar también si añadir sonidos cortos cuando el héroe salta, camina, cuando los enemigos rebotan al tocar con otros objetos, una semilla germina, un globo rebota...

**Comment by yagueto** [comment]
Cuando se pulsa en prefrencias para desactivar el sonido, la aplicación enseña una pantalla azul.

ERROR:

```
Error

menus/preferences.lua:30: attempt to index field 'ui_click' (a nil value)


Traceback

menus/preferences.lua:30: in function 'update'
menus/menuManager.lua:110: in function 'update'
menus/menuManager.lua:189: in function 'update'
screens/menu.lua:89: in function 'update'
main.lua:71: in function 'update'
[C]: in function 'xpcall'

```

**Comment by Autotren** [comment]
> Cuando se pulsa en prefrencias para desactivar el sonido, la aplicación enseña una pantalla azul.
> 
> ERROR:
> 
> ```
> Error
> 
> menus/preferences.lua:30: attempt to index field 'ui_click' (a nil value)
> 
> 
> Traceback
> 
> menus/preferences.lua:30: in function 'update'
> menus/menuManager.lua:110: in function 'update'
> menus/menuManager.lua:189: in function 'update'
> screens/menu.lua:89: in function 'update'
> main.lua:71: in function 'update'
> [C]: in function 'xpcall'
> ```

Solucionado

**Comment by yagueto** [comment]
He encontrado un pequeño bug:

Si se desactiva la música en el menú inicial, se vuelve a escuchar en el juego.

**Comment by Autotren** [comment]
Solucionado.
Ahora la música se desactiva globalmente.
