### ISSUE TITLE
Permitir al enemigo atravesar al jugador mientras esté parpadeando

### ISSUE THREAD

**Issue by MF-patino** [codemonsters/dizzy-balloon#58]
Con esto evitaríamos que se queden pillados ambos en el spawn

**Comment by Braisa** [comment]
Referencia al commit 85f3e1d229b3b8923322a7e2abc4818dfd56df63

Hice revert al anterior commit (9e84bd483598c90d5f906c68bb5adecfb5e73041) porque la forma en la que solucioné esta issue provocaba demasiados bugs.
